Fixes three errors caused by stricter gcc defaults.
gcc-15.1.0 throws an error on declaration/definition mismatches.

/p/vast1/rountree/repos/Spindle/src/client/biter/../../biter/linux_ids.c:27:14:
error: conflicting types for ‘biterc_get_rank’; have ‘unsigned int(int)’

/p/vast1/rountree/repos/Spindle/src/client/biter/../../biter/shmutil.c:242:6:
error: conflicting types for ‘update_shm_id’; have ‘void(shminfo_t *)’

/p/vast1/rountree/repos/Spindle/src/client/client/remap_exec.c:168:6:
error: conflicting types for ‘remap_executable’; have ‘void(int)’

Updates header files in each case.  Passes runTests.